name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'  # Выберите версию Node.js, которая вам нужна

      - name: Create index.html
        run: node index.js

      - name: Set up Google Cloud authentication
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > $HOME/gcloud.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project my-test-8cd41 --only hosting:prod
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json
